### ISSUE TITLE
Can we have a kustomizev3 manifest which can deploy KFP 0.5.1 with Tekton backend

### ISSUE THREAD

**Issue by animeshsingh** [IBM/KubeflowDojo#27]
cc @adrian555 @Tomcli

**Comment by Tomcli** [comment]
@adrian555 Do you know what's the best method to deploy kubeflow manifest using kustomizev3? The KFP team has the v3 manifest ready but they don't have it integrate with kfdef.

**Comment by adrian555** [comment]
if it is a kustomize v3 manifest, then you can just run `kustomize build --load_restrictor=none|kubectl apply -f -` in the directory containing the kustomization.yaml file. That is, you don't need `kfctl` or `kfdef` in the middle.

**Comment by animeshsingh** [comment]
ok - i was thinking more in context of larger kubeflow deployment on ibmcloud

a version of kfctl/kfdef/kustomize which deploys our implementation of kubeflow pipelines with tekton. We then ensure @shawnzhu is recommending that version as well.

**Comment by adrian555** [comment]
Will this be a standalone kfp+tekton installation or part of the kubeflow (ie. part of the kfctl_ibm.yaml)? If it is the latter case, we will need some modification in the `kfctl_ibm.yaml` and the `kubeflow-apps` stacks for ibm. Then it will be able to install with the `kfctl` command.

But likely should confirm @Tomcli whether the v3 kfp manifests contain kfp0.5.1 or else.

**Comment by Tomcli** [comment]
I'm wondering is there a single kustomization.yaml for deploying all the Kubeflow component? With the v3 manifest in kubeflow right now, we don't have an easy way to maintain all our custom configuration in a single place. Also can kfdef apply the overlays on v3 kustomization base? if so then we can keep using kfdef as our single entrypoint.

[Here](https://github.com/kubeflow/manifests/tree/master/pipeline) is the pipeline v3 kustomization.

**Comment by Tomcli** [comment]
> But likely should confirm @Tomcli whether the v3 kfp manifests contain kfp0.5.1 or else.

The v3 kustomization base should work for kfp 0.4 and above. Right now their v3 base image is kfp 1.0-rc2

**Comment by adrian555** [comment]
> I'm wondering is there a single kustomization.yaml for deploying all the Kubeflow component?

It does not exist in the manifests repo but you can write one simply by adding all the components as the resources to a kustomization.yaml.

> Also can kfdef apply the overlays on v3 kustomization base? if so then we can keep using kfdef as our single entrypoint.

The purpose of kustomize v3 update includes removing the parameters and overlays fields from the kfdef. But the source code processing the overlays etc is still there. So in theory, it can. However, if we still need such ability, why not we just stick with the pre-v3 configuration?

Seriously with the recent trouble we encountered trying to support dex version of kfctl_ibm.yaml, it makes me think we should reconsider whether continue to depend on kfdef and kfctl.

**Comment by adrian555** [comment]
done through #37
